apiVersion: v1
kind: Service
metadata:
  name: cicd-gateway-service
  namespace: {{ .Release.Namespace }}
  labels:
    chart: cicd-gateway
    app: cicd-gateway
    release: {{ .Release.Name }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.internalPort }}
    targetPort: port-{{ .Values.service.internalPort | toString }}
    protocol: TCP
    name: port-{{ .Values.service.internalPort | toString }}
  selector:
    app: cicd-gateway