apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: spinless-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    app: spinless
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: spinless.exchange.om2.com
    http:
      paths:
      - backend:
          serviceName: spinless-service
          servicePort: {{ .Values.service.internalPort }}