image:
  repository: scalecube/spinless
  tag: develop
  pullPolicy: Always

spin:
  auth_token: ascdefgh
  api: http://localhost

env:
  timestamp: 111111

podTemplate:
  annotations: {}

  labels: {}

nodeSelector:
  environment: dev

service:
  internalPort: 5000
  annotations: {}
  type: NodePort

ingress:
  dnsname: scalecube-spinless
